openapi: 3.1.0
info:
  title: Fast ACCOUNT_COSTS METRICS API
  version: 0.1.0
tags:
- name: METRICS
paths:
  /metrics/:
    get:
      tags:
      - METRICS
      summary: Get Metrics List
      description: 'Returns list of metrics currently supported by the profile service

        :param auth: The authorization token for the request.

        :return: A metrics list response containing the list of metrics.'
      operationId: get_metrics_list_metrics__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsFetchResponse'
      security:
      - HTTPBearer: []
      - HTTPBearer: []
components:
  schemas:
    MetricsFetchResponse:
      properties:
        metrics:
          items:
            type: string
          type: array
          title: Metrics
      type: object
      required:
      - metrics
      title: MetricsFetchResponse
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
servers:
- url: https://api.myaltimate.com
  description: Base URL reconciled from apis.yml
