openapi: 3.1.0
info:
  title: Fast ACCOUNT_COSTS REGISTRY API
  version: 0.1.0
tags:
- name: REGISTRY
paths:
  /registries/:
    get:
      tags:
      - REGISTRY
      summary: Get Registry
      description: 'Gets all registries from db

        :param db: database session

        :param auth: auth token.'
      operationId: get_registry_registries__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistryFetchMultipleResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 400 Get Registry Registries  Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 403 Get Registry Registries  Get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
    post:
      tags:
      - REGISTRY
      summary: Create Registry
      description: 'Create a new registry

        :param db: database session

        :param registry_creation_request: registry creation request

        :param auth: auth token. Also gets the user_id from the token

        return: RegistryCreationResponse.'
      operationId: create_registry_registries__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistryCreationRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistryCreationResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 400 Create Registry Registries  Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 403 Create Registry Registries  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
  /registries/id/{registry_id}:
    get:
      tags:
      - REGISTRY
      summary: Get Registry By Id
      description: 'Gets the registru by id

        :param registry: registry object fetched from db

        :param auth: auth token.'
      operationId: get_registry_by_id_registries_id__registry_id__get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: registry_id
        in: path
        required: true
        schema:
          type: integer
          title: Registry Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistryFetchResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Registry By Id Registries Id  Registry Id  Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Registry By Id Registries Id  Registry Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /registries/name/{registry_name}:
    get:
      tags:
      - REGISTRY
      summary: Get Registry By Name
      description: 'Gets the registru by id

        :param registry_name: registry name

        :param db: database session

        :param auth: auth token.'
      operationId: get_registry_by_name_registries_name__registry_name__get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: registry_name
        in: path
        required: true
        schema:
          type: string
          title: Registry Name
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistryFetchResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Registry By Name Registries Name  Registry Name  Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Registry By Name Registries Name  Registry Name  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /registries/{registry_id}:
    put:
      tags:
      - REGISTRY
      summary: Update Registry
      description: 'Update the registry by the provided information

        :param db: database session

        :param registry: registry object fetched from db. Check if the registry exists

        :param registry_update_request: registry update request

        :param auth: auth token. Also gets the user_id from the token

        :param registry_id: registry id. This is the path param'
      operationId: update_registry_registries__registry_id__put
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: registry_id
        in: path
        required: true
        schema:
          type: integer
          title: Registry Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistryUpdateRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistryUpdateResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Update Registry Registries  Registry Id  Put
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Update Registry Registries  Registry Id  Put
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - REGISTRY
      summary: Delete Registry
      description: 'Deletes registry. If already deleted, returns 404

        db: Session = Depends(get_db) is a dependency injection which returns the db session with the tenant

        registry_id: registry to delete

        registry: registry object fetched from db which needs to be deleted

        auth=Depends(has_token) is a dependency injection which validates and returns the user_id'
      operationId: delete_registry_registries__registry_id__delete
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: registry_id
        in: path
        required: true
        schema:
          type: integer
          title: Registry Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistryDeletionResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Delete Registry Registries  Registry Id  Delete
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Delete Registry Registries  Registry Id  Delete
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    RegistryCreationRequest:
      properties:
        name:
          type: string
          title: Name
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        status:
          anyOf:
          - type: string
          - type: 'null'
          title: Status
      type: object
      required:
      - name
      title: RegistryCreationRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    RegistryCreationResponse:
      properties:
        id:
          type: integer
          title: Id
        name:
          type: string
          title: Name
        status:
          type: string
          title: Status
        message:
          type: string
          title: Message
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
      type: object
      required:
      - id
      - name
      - status
      - message
      title: RegistryCreationResponse
    RegistryUpdateRequest:
      properties:
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        status:
          anyOf:
          - type: string
          - type: 'null'
          title: Status
      type: object
      title: RegistryUpdateRequest
    RegistryFetchResponse:
      properties:
        id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Id
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        created_by:
          anyOf:
          - type: string
          - type: 'null'
          title: Created By
        last_modified_by:
          anyOf:
          - type: string
          - type: 'null'
          title: Last Modified By
        status:
          anyOf:
          - type: string
          - type: 'null'
          title: Status
      type: object
      title: RegistryFetchResponse
    RegistryUpdateResponse:
      properties:
        id:
          type: integer
          title: Id
        name:
          type: string
          title: Name
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        created_by:
          type: string
          title: Created By
        last_modified_by:
          type: string
          title: Last Modified By
        status:
          type: string
          title: Status
        message:
          type: string
          title: Message
      type: object
      required:
      - id
      - name
      - created_by
      - last_modified_by
      - status
      - message
      title: RegistryUpdateResponse
    RegistryFetchMultipleResponse:
      properties:
        registries:
          items:
            $ref: '#/components/schemas/RegistryFetchResponse'
          type: array
          title: Registries
      type: object
      required:
      - registries
      title: RegistryFetchMultipleResponse
    RegistryDeletionResponse:
      properties:
        message:
          type: string
          title: Message
      type: object
      required:
      - message
      title: RegistryDeletionResponse
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
