openapi: 3.1.0
info:
  title: Fast ACCOUNT_COSTS PRESET API
  version: 0.1.0
tags:
- name: PRESET
paths:
  /preset/:
    get:
      tags:
      - PRESET
      summary: Get Presets
      operationId: get_presets_preset__get
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: type
        in: query
        required: false
        schema:
          type: string
          title: Type
      - name: applicable_for
        in: query
        required: false
        schema:
          type: string
          title: Applicable For
      - name: x-tenant
        in: header
        required: true
        schema:
          type: string
          title: X-Tenant
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllPresetResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Presets Preset  Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Presets Preset  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - PRESET
      summary: Create Preset
      operationId: create_preset_preset__post
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: x-tenant
        in: header
        required: true
        schema:
          type: string
          title: X-Tenant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePresetRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePresetResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Create Preset Preset  Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Create Preset Preset  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /preset/{preset_id}:
    get:
      tags:
      - PRESET
      summary: Get Preset
      operationId: get_preset_preset__preset_id__get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: preset_id
        in: path
        required: true
        schema:
          type: integer
          title: Preset Id
      - name: x-tenant
        in: header
        required: true
        schema:
          type: string
          title: X-Tenant
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPresetResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Preset Preset  Preset Id  Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Preset Preset  Preset Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    patch:
      tags:
      - PRESET
      summary: Update Preset
      operationId: update_preset_preset__preset_id__patch
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: preset_id
        in: path
        required: true
        schema:
          type: integer
          title: Preset Id
      - name: x-tenant
        in: header
        required: true
        schema:
          type: string
          title: X-Tenant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePresetRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdatePresetResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Update Preset Preset  Preset Id  Patch
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Update Preset Preset  Preset Id  Patch
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - PRESET
      summary: Delete Preset
      operationId: delete_preset_preset__preset_id__delete
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: preset_id
        in: path
        required: true
        schema:
          type: integer
          title: Preset Id
      - name: x-tenant
        in: header
        required: true
        schema:
          type: string
          title: X-Tenant
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeletePresetResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Delete Preset Preset  Preset Id  Delete
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Delete Preset Preset  Preset Id  Delete
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    UpdatePresetRequest:
      properties:
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        data:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Data
        applicable_for:
          anyOf:
          - type: string
          - type: 'null'
          title: Applicable For
        type:
          anyOf:
          - $ref: '#/components/schemas/Preset'
          - type: 'null'
      type: object
      title: UpdatePresetRequest
    PresetModel:
      properties:
        name:
          type: string
          title: Name
        data:
          additionalProperties: true
          type: object
          title: Data
        applicable_for:
          type: string
          title: Applicable For
        type:
          $ref: '#/components/schemas/Preset'
        id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Id
      type: object
      required:
      - name
      - data
      - applicable_for
      - type
      title: PresetModel
    Preset:
      type: string
      enum:
      - filter
      - column_picker
      - optin_features
      title: Preset
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    GetPresetResponse:
      properties:
        preset:
          $ref: '#/components/schemas/PresetModel'
      type: object
      required:
      - preset
      title: GetPresetResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    UpdatePresetResponse:
      properties:
        preset_id:
          type: integer
          title: Preset Id
      type: object
      required:
      - preset_id
      title: UpdatePresetResponse
    DeletePresetResponse:
      properties:
        preset_id:
          type: integer
          title: Preset Id
      type: object
      required:
      - preset_id
      title: DeletePresetResponse
    GetAllPresetResponse:
      properties:
        presets:
          items:
            $ref: '#/components/schemas/PresetModel'
          type: array
          title: Presets
      type: object
      required:
      - presets
      title: GetAllPresetResponse
    CreatePresetResponse:
      properties:
        preset_id:
          type: integer
          title: Preset Id
      type: object
      required:
      - preset_id
      title: CreatePresetResponse
    CreatePresetRequest:
      properties:
        name:
          type: string
          title: Name
        data:
          additionalProperties: true
          type: object
          title: Data
        applicable_for:
          type: string
          title: Applicable For
        type:
          $ref: '#/components/schemas/Preset'
      type: object
      required:
      - name
      - data
      - applicable_for
      - type
      title: CreatePresetRequest
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
servers:
- url: https://api.myaltimate.com
  description: Base URL reconciled from apis.yml
