openapi: 3.1.0
info:
  title: Fast ACCOUNT_COSTS EXPERIMENTATION API
  version: 0.1.0
tags:
- name: EXPERIMENTATION
paths:
  /experimentation/:
    get:
      tags:
      - EXPERIMENTATION
      summary: Get Experiments
      operationId: get_experiments_experimentation__get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: sort_key
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          default: name
          title: Sort Key
      - name: sort_order
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          default: desc
          title: Sort Order
      - name: users
        in: query
        required: false
        schema:
          type: array
          items:
            type: integer
          default: []
          title: Users
      - name: status
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
          default: []
          title: Status
      - name: entities
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
          default: []
          title: Entities
      - name: page
        in: query
        required: false
        schema:
          type: integer
          minimum: 1
          description: Page number
          default: 1
          title: Page
        description: Page number
      - name: size
        in: query
        required: false
        schema:
          type: integer
          maximum: 100
          minimum: 1
          description: Page size
          default: 50
          title: Size
        description: Page size
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_ExperimentItem_'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Experiments Experimentation  Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Experiments Experimentation  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - EXPERIMENTATION
      summary: Create Experiment
      operationId: create_experiment_experimentation__post
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExperimentCreateRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response Create Experiment Experimentation  Post
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Create Experiment Experimentation  Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Create Experiment Experimentation  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /experimentation/{item_id}:
    get:
      tags:
      - EXPERIMENTATION
      summary: Get Experiment By Id
      operationId: get_experiment_by_id_experimentation__item_id__get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: item_id
        in: path
        required: true
        schema:
          type: integer
          title: Item Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExperimentItem'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Experiment By Id Experimentation  Item Id  Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Experiment By Id Experimentation  Item Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    patch:
      tags:
      - EXPERIMENTATION
      summary: Update Experiment
      operationId: update_experiment_experimentation__item_id__patch
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: item_id
        in: path
        required: true
        schema:
          type: string
          title: Item Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExperimentUpdateRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response Update Experiment Experimentation  Item Id  Patch
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Update Experiment Experimentation  Item Id  Patch
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Update Experiment Experimentation  Item Id  Patch
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /experimentation/metadata/summary:
    get:
      tags:
      - EXPERIMENTATION
      summary: Get Experiment Summary
      operationId: get_experiment_summary_experimentation_metadata_summary_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Get Experiment Summary Experimentation Metadata Summary Get
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 400 Get Experiment Summary Experimentation Metadata Summary Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 403 Get Experiment Summary Experimentation Metadata Summary Get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
  /experimentation/{item_id}/status:
    patch:
      tags:
      - EXPERIMENTATION
      summary: Update Experiment Status
      operationId: update_experiment_status_experimentation__item_id__status_patch
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: item_id
        in: path
        required: true
        schema:
          type: string
          title: Item Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExperimentUpdateRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response Update Experiment Status Experimentation  Item Id  Status Patch
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Update Experiment Status Experimentation  Item Id  Status Patch
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Update Experiment Status Experimentation  Item Id  Status Patch
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /experimentation/schema/metadata:
    get:
      tags:
      - EXPERIMENTATION
      summary: Get Schema Metadata
      operationId: get_schema_metadata_experimentation_schema_metadata_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SchemaMetadataItem'
                type: array
                title: Response Get Schema Metadata Experimentation Schema Metadata Get
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 400 Get Schema Metadata Experimentation Schema Metadata Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 403 Get Schema Metadata Experimentation Schema Metadata Get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
components:
  schemas:
    ExperimentMetric:
      properties:
        metric_type:
          type: string
          title: Metric Type
      type: object
      required:
      - metric_type
      title: ExperimentMetric
    ExperimentItem:
      properties:
        id:
          type: integer
          title: Id
        name:
          type: string
          title: Name
        hypothesis:
          type: string
          title: Hypothesis
        effort_level:
          anyOf:
          - type: string
          - type: 'null'
          title: Effort Level
        experiment_start:
          type: string
          format: date-time
          title: Experiment Start
        experiment_end:
          type: string
          format: date-time
          title: Experiment End
        instructions:
          type: string
          title: Instructions
        experiment_status:
          $ref: '#/components/schemas/ExperimentStatus'
        entities:
          items:
            $ref: '#/components/schemas/ExperimentEntity'
          type: array
          title: Entities
        created_by:
          type: integer
          title: Created By
        created_on:
          type: string
          format: date-time
          title: Created On
      type: object
      required:
      - id
      - name
      - hypothesis
      - experiment_start
      - experiment_end
      - instructions
      - experiment_status
      - entities
      - created_by
      - created_on
      title: ExperimentItem
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ExperimentEntity:
      properties:
        entity_rk:
          anyOf:
          - type: integer
          - type: string
          title: Entity Rk
        entity_type:
          type: string
          title: Entity Type
        entity_name:
          type: string
          title: Entity Name
        insights:
          anyOf:
          - items:
              additionalProperties: true
              type: object
            type: array
          - type: 'null'
          title: Insights
      type: object
      required:
      - entity_rk
      - entity_type
      - entity_name
      title: ExperimentEntity
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Page_ExperimentItem_:
      properties:
        items:
          items:
            $ref: '#/components/schemas/ExperimentItem'
          type: array
          title: Items
        total:
          anyOf:
          - type: integer
            minimum: 0.0
          - type: 'null'
          title: Total
        page:
          anyOf:
          - type: integer
            minimum: 1.0
          - type: 'null'
          title: Page
        size:
          anyOf:
          - type: integer
            minimum: 1.0
          - type: 'null'
          title: Size
        pages:
          anyOf:
          - type: integer
            minimum: 0.0
          - type: 'null'
          title: Pages
      type: object
      required:
      - items
      - total
      - page
      - size
      title: Page[ExperimentItem]
    ExperimentStatus:
      type: string
      enum:
      - Planned
      - In Progress
      - Completed
      - Aborted
      title: ExperimentStatus
    ExperimentUpdateRequest:
      properties:
        experiment_status:
          $ref: '#/components/schemas/ExperimentStatusUpdateReq'
      type: object
      required:
      - experiment_status
      title: ExperimentUpdateRequest
    ExperimentStatusUpdateReq:
      type: string
      enum:
      - Planned
      - In Progress
      - Aborted
      - success
      - failure
      title: ExperimentStatusUpdateReq
    ExperimentCreateRequest:
      properties:
        name:
          type: string
          title: Name
        hypothesis:
          type: string
          title: Hypothesis
        experiment_start:
          type: string
          format: date-time
          title: Experiment Start
        experiment_end:
          type: string
          format: date-time
          title: Experiment End
        instructions:
          type: string
          title: Instructions
        effort_level:
          type: string
          title: Effort Level
        entities:
          items:
            $ref: '#/components/schemas/ExperimentEntity'
          type: array
          title: Entities
        metrics:
          items:
            $ref: '#/components/schemas/ExperimentMetric'
          type: array
          title: Metrics
      type: object
      required:
      - name
      - hypothesis
      - experiment_start
      - experiment_end
      - instructions
      - effort_level
      - entities
      - metrics
      title: ExperimentCreateRequest
    SchemaMetadataItem:
      properties:
        rk:
          type: string
          title: Rk
        name:
          type: string
          title: Name
      type: object
      required:
      - rk
      - name
      title: SchemaMetadataItem
      description: Response item for schema metadata endpoint.
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
servers:
- url: https://api.myaltimate.com
  description: Base URL reconciled from apis.yml
