openapi: 3.1.0
info:
  title: Fast ACCOUNT_COSTS PERMISSION API
  version: 0.1.0
tags:
- name: PERMISSION
paths:
  /permissions/:
    get:
      tags:
      - PERMISSION
      summary: Role Get All
      operationId: role_get_all_permissions__get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: search
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Search
      - name: sortOrder
        in: query
        required: false
        schema:
          type: string
          default: asc
          title: Sortorder
      - name: sortColumn
        in: query
        required: false
        schema:
          type: string
          default: name
          title: Sortcolumn
      - name: page
        in: query
        required: false
        schema:
          type: integer
          minimum: 1
          description: Page number
          default: 1
          title: Page
        description: Page number
      - name: size
        in: query
        required: false
        schema:
          type: integer
          maximum: 100
          minimum: 1
          description: Page size
          default: 50
          title: Size
        description: Page size
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_RoleSummaryResponse_'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Role Get All Permissions  Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Role Get All Permissions  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - PERMISSION
      summary: Role Add
      operationId: role_add_permissions__post
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleAddIn'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolePermissionFull'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Role Add Permissions  Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Role Add Permissions  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /permissions/all:
    get:
      tags:
      - PERMISSION
      summary: Permissions Get All
      operationId: permissions_get_all_permissions_all_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PermissionResponse'
                type: array
                title: Response Permissions Get All Permissions All Get
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 400 Permissions Get All Permissions All Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 403 Permissions Get All Permissions All Get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
  /permissions/{role_uuid}:
    get:
      tags:
      - PERMISSION
      summary: Role Get One
      operationId: role_get_one_permissions__role_uuid__get
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: role_uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Role Uuid
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolePermissionFull'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Role Get One Permissions  Role Uuid  Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Role Get One Permissions  Role Uuid  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    patch:
      tags:
      - PERMISSION
      summary: Role Edit
      operationId: role_edit_permissions__role_uuid__patch
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: role_uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Role Uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleEditIn'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolePermissionFull'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Role Edit Permissions  Role Uuid  Patch
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Role Edit Permissions  Role Uuid  Patch
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - PERMISSION
      summary: Role Delete
      operationId: role_delete_permissions__role_uuid__delete
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: role_uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Role Uuid
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Role Delete Permissions  Role Uuid  Delete
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Role Delete Permissions  Role Uuid  Delete
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    PermissionResponse:
      properties:
        uuid:
          type: string
          format: uuid
          title: Uuid
        group:
          type: string
          title: Group
        title:
          type: string
          title: Title
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
      type: object
      required:
      - uuid
      - group
      - title
      - name
      - description
      title: PermissionResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    RoleEditIn:
      properties:
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        permissions:
          anyOf:
          - items:
              type: string
              format: uuid
            type: array
          - type: 'null'
          title: Permissions
      type: object
      title: RoleEditIn
    StandardResponse:
      properties:
        ok:
          type: boolean
          title: Ok
      type: object
      required:
      - ok
      title: StandardResponse
    RoleAddIn:
      properties:
        title:
          type: string
          title: Title
        description:
          type: string
          title: Description
        permissions:
          items:
            type: string
            format: uuid
          type: array
          title: Permissions
      type: object
      required:
      - title
      - description
      - permissions
      title: RoleAddIn
    RolePermissionFull:
      properties:
        role_name:
          type: string
          title: Role Name
        role_description:
          type: string
          title: Role Description
        role_title:
          type: string
          title: Role Title
        is_custom:
          type: boolean
          title: Is Custom
        permission:
          items:
            $ref: '#/components/schemas/PermissionsFull'
          type: array
          title: Permission
      type: object
      required:
      - role_name
      - role_description
      - role_title
      - is_custom
      - permission
      title: RolePermissionFull
    RoleSummaryResponse:
      properties:
        uuid:
          type: string
          format: uuid
          title: Uuid
        role_title:
          type: string
          title: Role Title
        role_description:
          type: string
          title: Role Description
        is_custom:
          type: boolean
          title: Is Custom
        count:
          type: integer
          title: Count
      type: object
      required:
      - uuid
      - role_title
      - role_description
      - is_custom
      - count
      title: RoleSummaryResponse
    Page_RoleSummaryResponse_:
      properties:
        items:
          items:
            $ref: '#/components/schemas/RoleSummaryResponse'
          type: array
          title: Items
        total:
          anyOf:
          - type: integer
            minimum: 0.0
          - type: 'null'
          title: Total
        page:
          anyOf:
          - type: integer
            minimum: 1.0
          - type: 'null'
          title: Page
        size:
          anyOf:
          - type: integer
            minimum: 1.0
          - type: 'null'
          title: Size
        pages:
          anyOf:
          - type: integer
            minimum: 0.0
          - type: 'null'
          title: Pages
      type: object
      required:
      - items
      - total
      - page
      - size
      title: Page[RoleSummaryResponse]
    PermissionsFull:
      properties:
        uuid:
          type: string
          format: uuid
          title: Uuid
        name:
          type: string
          title: Name
        title:
          type: string
          title: Title
        description:
          type: string
          title: Description
        group:
          anyOf:
          - type: string
          - type: 'null'
          title: Group
      type: object
      required:
      - uuid
      - name
      - title
      - description
      title: PermissionsFull
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
servers:
- url: https://api.myaltimate.com
  description: Base URL reconciled from apis.yml
