openapi: 3.1.0
info:
  title: Fast ACCOUNT_COSTS Auth Health API
  version: 0.1.0
tags:
- name: Auth Health
paths:
  /auth_health:
    get:
      summary: Auth Health Check
      operationId: auth_health_check_auth_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      tags:
      - Auth Health
components:
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
