openapi: 3.1.0
info:
  title: Fast ACCOUNT_COSTS DEFINITIONS API
  version: 0.1.0
tags:
- name: DEFINITIONS
paths:
  /definitions/:
    get:
      tags:
      - DEFINITIONS
      summary: Get Definitions
      description: 'Get templates for a given table schema and data store type

        is_operation_allowed: bool = Depends(is_tenant_allowed),

        :param auth: Depends(has_token)

        :return: Dict containing templates'
      operationId: get_definitions_definitions__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
components:
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
servers:
- url: https://api.myaltimate.com
  description: Base URL reconciled from apis.yml
