openapi: 3.1.0
info:
  title: Fast ACCOUNT_COSTS RESOURCES API
  version: 0.1.0
tags:
- name: RESOURCES
paths:
  /data_stores/{data_store_id}/resources:
    post:
      tags:
      - RESOURCES
      summary: Create Resource
      description: 'Create a data store in the database.

        :param db: The database session for accessing the database.

        :param data_store_creation_request: The data store creation request containing the data store definition and other

        metadata.

        :param auth: The authorization token for the request.

        :return: A data store creation response containing the data store ID, and a message.'
      operationId: create_resource_data_stores__data_store_id__resources_post
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: data_store_id
        in: path
        required: true
        schema:
          type: integer
          title: Data Store Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceCreationRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceCreationResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Create Resource Data Stores  Data Store Id  Resources Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Create Resource Data Stores  Data Store Id  Resources Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    get:
      tags:
      - RESOURCES
      summary: Get Resource
      description: 'Get resources given data store id from the database.

        :param db: The database session for accessing the database.'
      operationId: get_resource_data_stores__data_store_id__resources_get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: data_store_id
        in: path
        required: true
        schema:
          type: integer
          title: Data Store Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceFetchResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Resource Data Stores  Data Store Id  Resources Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Resource Data Stores  Data Store Id  Resources Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      tags:
      - RESOURCES
      summary: Update Resource
      description: ':param db: The database session for accessing the database.

        :param auth: The authorization token for the request.

        :param data_store_id: The id of the data store.

        :param resource_update_request: The data required for updating resource.

        :return: resource id'
      operationId: update_resource_data_stores__data_store_id__resources_put
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: data_store_id
        in: path
        required: true
        schema:
          type: integer
          title: Data Store Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceUpdateRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceUpdateResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Update Resource Data Stores  Data Store Id  Resources Put
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Update Resource Data Stores  Data Store Id  Resources Put
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /data_stores/{data_store_id}/resources/{resource_id}/metadata:
    post:
      tags:
      - RESOURCES
      summary: Add Metadata
      description: 'Get resources given data store id from the database.

        :param db: The database session for accessing the database.'
      operationId: add_metadata_data_stores__data_store_id__resources__resource_id__metadata_post
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: data_store_id
        in: path
        required: true
        schema:
          type: integer
          title: Data Store Id
      - name: resource_id
        in: path
        required: true
        schema:
          type: integer
          title: Resource Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetadataCreationRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataCreationResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Add Metadata Data Stores  Data Store Id  Resources  Resource Id  Metadata Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Add Metadata Data Stores  Data Store Id  Resources  Resource Id  Metadata Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    MetadataCreationRequest:
      properties:
        resource:
          additionalProperties: true
          type: object
          title: Resource
        columns:
          additionalProperties: true
          type: object
          title: Columns
      type: object
      required:
      - resource
      - columns
      title: MetadataCreationRequest
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ResourceCreationRequest:
      properties:
        identifier:
          type: string
          title: Identifier
        resource_schema:
          additionalProperties: true
          type: object
          title: Resource Schema
        options:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Options
      type: object
      required:
      - identifier
      - resource_schema
      title: ResourceCreationRequest
    ResourceCreationResponse:
      properties:
        id:
          type: integer
          title: Id
        message:
          type: string
          title: Message
      type: object
      required:
      - id
      - message
      title: ResourceCreationResponse
    ResourceResponse:
      properties:
        id:
          type: integer
          title: Id
        identifier:
          type: string
          title: Identifier
        options:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Options
      type: object
      required:
      - id
      - identifier
      title: ResourceResponse
    MetadataCreationResponse:
      properties:
        message:
          type: string
          title: Message
      type: object
      required:
      - message
      title: MetadataCreationResponse
    ResourceUpdateRequest:
      properties:
        identifier:
          type: string
          title: Identifier
        resource_schema:
          additionalProperties: true
          type: object
          title: Resource Schema
        options:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Options
      type: object
      required:
      - identifier
      - resource_schema
      title: ResourceUpdateRequest
    ResourceUpdateResponse:
      properties:
        id:
          type: integer
          title: Id
        message:
          type: string
          title: Message
      type: object
      required:
      - id
      - message
      title: ResourceUpdateResponse
    ResourceFetchResponse:
      properties:
        resources:
          items:
            $ref: '#/components/schemas/ResourceResponse'
          type: array
          title: Resources
      type: object
      required:
      - resources
      title: ResourceFetchResponse
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
