openapi: 3.1.0
info:
  title: Fast ACCOUNT_COSTS SUMMARY API
  version: 0.1.0
tags:
- name: SUMMARY
paths:
  /summary/:
    post:
      tags:
      - SUMMARY
      summary: Get Graph
      operationId: get_graph_summary__post
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: x-tenant
        in: header
        required: true
        schema:
          type: string
          title: X-Tenant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummaryGraphRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummaryGraphResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Graph Summary  Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Graph Summary  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /summary/comparison:
    post:
      tags:
      - SUMMARY
      summary: Get Comparison
      operationId: get_comparison_summary_comparison_post
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: x-tenant
        in: header
        required: true
        schema:
          type: string
          title: X-Tenant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComparisonRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComparisonResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Comparison Summary Comparison Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Comparison Summary Comparison Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /summary/insights:
    get:
      tags:
      - SUMMARY
      summary: Get Insights
      operationId: get_insights_summary_insights_get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: period
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/Period'
          default: 30
      - name: insight_type
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/InsightType'
          default: cost
      - name: summary_type
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/SummaryType'
          default: header
      - name: x-tenant
        in: header
        required: true
        schema:
          type: string
          title: X-Tenant
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummaryInsightsResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Insights Summary Insights Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Insights Summary Insights Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /summary/side_panel:
    get:
      tags:
      - SUMMARY
      summary: Get Side Panel Insights
      operationId: get_side_panel_insights_summary_side_panel_get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: period
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/Period'
          default: 365
      - name: insight_type
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/InsightType'
          default: cost
      - name: summary_type
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/SummaryType'
          default: side_panel
      - name: x-tenant
        in: header
        required: true
        schema:
          type: string
          title: X-Tenant
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummarySidePanelResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Side Panel Insights Summary Side Panel Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Side Panel Insights Summary Side Panel Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /summary/config:
    get:
      tags:
      - SUMMARY
      summary: Get Config
      operationId: get_config_summary_config_get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: x-tenant
        in: header
        required: true
        schema:
          type: string
          title: X-Tenant
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummaryConfigResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Config Summary Config Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Config Summary Config Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - SUMMARY
      summary: Post Config
      operationId: post_config_summary_config_post
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: x-tenant
        in: header
        required: true
        schema:
          type: string
          title: X-Tenant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummaryConfigRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response Post Config Summary Config Post
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Post Config Summary Config Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Post Config Summary Config Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /summary/experimentation_savings:
    get:
      tags:
      - SUMMARY
      summary: Get Experimentation Savings
      operationId: get_experimentation_savings_summary_experimentation_savings_get
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: x-tenant
        in: header
        required: true
        schema:
          type: string
          title: X-Tenant
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummaryTotalSavingsResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Get Experimentation Savings Summary Experimentation Savings Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Get Experimentation Savings Summary Experimentation Savings Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    SidePanelModel:
      properties:
        title:
          type: string
          title: Title
        value:
          type: string
          title: Value
        attributes:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Attributes
      type: object
      required:
      - title
      - value
      title: SidePanelModel
    Period:
      type: integer
      enum:
      - 365
      - 29
      - 30
      - 7
      - 1
      - 28
      title: Period
    TopInfoItem:
      properties:
        value:
          type: number
          title: Value
        display:
          type: boolean
          title: Display
        max_value:
          anyOf:
          - type: number
          - type: 'null'
          title: Max Value
        min_value:
          anyOf:
          - type: number
          - type: 'null'
          title: Min Value
        color:
          anyOf:
          - type: string
          - type: 'null'
          title: Color
      additionalProperties: true
      type: object
      required:
      - value
      - display
      title: TopInfoItem
    SummaryTotalSavingsResponse:
      properties:
        total_cost_savings_ui:
          type: string
          title: Total Cost Savings Ui
        overall_actual_cost_savings_ui:
          type: string
          title: Overall Actual Cost Savings Ui
        experimentation_savings_ui:
          type: string
          title: Experimentation Savings Ui
      type: object
      required:
      - total_cost_savings_ui
      - overall_actual_cost_savings_ui
      - experimentation_savings_ui
      title: SummaryTotalSavingsResponse
    TimeSidePanelModel:
      properties:
        title:
          type: string
          title: Title
        value:
          type: string
          title: Value
        attributes:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Attributes
      type: object
      required:
      - title
      - value
      title: TimeSidePanelModel
    InsightType:
      type: string
      enum:
      - cost
      - storage
      - governance
      - cost_overall
      - auto
      title: InsightType
    SummaryInsightsResponse:
      properties:
        insight_type:
          $ref: '#/components/schemas/InsightType'
        summary_type:
          $ref: '#/components/schemas/SummaryType'
        summary_data:
          items:
            $ref: '#/components/schemas/InsightData'
          type: array
          title: Summary Data
      type: object
      required:
      - insight_type
      - summary_type
      - summary_data
      title: SummaryInsightsResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ComparisonResponse:
      properties:
        data:
          items:
            additionalProperties: true
            type: object
          type: array
          title: Data
      type: object
      required:
      - data
      title: ComparisonResponse
    SummaryConfigRequest:
      properties:
        dormant_period:
          type: integer
          title: Dormant Period
      type: object
      required:
      - dormant_period
      title: SummaryConfigRequest
    SummarySidePanelResponse:
      properties:
        total_annual_spend:
          anyOf:
          - $ref: '#/components/schemas/SidePanelModel'
          - type: 'null'
        total_annual_savings:
          anyOf:
          - $ref: '#/components/schemas/SidePanelModel'
          - type: 'null'
        total_time_savings:
          anyOf:
          - $ref: '#/components/schemas/TimeSidePanelModel'
          - type: 'null'
      type: object
      title: SummarySidePanelResponse
    SummaryType:
      type: string
      enum:
      - header
      - insight
      - side_panel
      title: SummaryType
    ComparisonRequest:
      properties:
        period:
          $ref: '#/components/schemas/Period'
      type: object
      required:
      - period
      title: ComparisonRequest
    SummaryGraphResponse:
      properties:
        graph_data:
          items:
            additionalProperties: true
            type: object
          type: array
          title: Graph Data
        top_info:
          anyOf:
          - additionalProperties:
              $ref: '#/components/schemas/TopInfoItem'
            type: object
          - type: 'null'
          title: Top Info
      type: object
      required:
      - graph_data
      title: SummaryGraphResponse
    SummaryConfigResponse:
      properties:
        dormant_period:
          type: integer
          title: Dormant Period
      type: object
      required:
      - dormant_period
      title: SummaryConfigResponse
    SummaryGraphRequest:
      properties:
        period:
          $ref: '#/components/schemas/Period'
        insight_type:
          $ref: '#/components/schemas/InsightType'
      type: object
      required:
      - period
      - insight_type
      title: SummaryGraphRequest
    InsightData:
      properties:
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        value:
          anyOf:
          - type: string
          - type: 'null'
          title: Value
        attributes:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Attributes
      type: object
      title: InsightData
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
