openapi: 3.1.0
info:
  title: Fast ACCOUNT_COSTS SUPERTOKENS API
  version: 0.1.0
tags:
- name: SUPERTOKENS
paths:
  /supertokens/:
    get:
      tags:
      - SUPERTOKENS
      summary: List Tenants
      description: 'Lists all tenants in SuperTokens

        :return: List of tenants'
      operationId: list_tenants_supertokens__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 403 List Tenants Supertokens  Get
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
  /supertokens/create-tenant:
    post:
      tags:
      - SUPERTOKENS
      summary: Create Supertokens Tenant
      description: 'Creates a new tenant in SuperTokens

        :return: ok status and optional message.'
      operationId: create_supertokens_tenant_supertokens_create_tenant_post
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: new_tenant
        in: query
        required: true
        schema:
          type: string
          title: New Tenant
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Create Supertokens Tenant Supertokens Create Tenant Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Create Supertokens Tenant Supertokens Create Tenant Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /supertokens/update-tenant-thirdparty:
    post:
      tags:
      - SUPERTOKENS
      summary: Update Tenant Thirdparty
      description: 'Updates the tenant with the third party config

        :return: ok status and optional message.'
      operationId: update_tenant_thirdparty_supertokens_update_tenant_thirdparty_post
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: new_tenant
        in: query
        required: true
        schema:
          type: string
          title: New Tenant
      - name: client_id
        in: query
        required: true
        schema:
          type: string
          title: Client Id
      - name: client_secret
        in: query
        required: true
        schema:
          type: string
          title: Client Secret
      - name: oidc_discovery_endpoint
        in: query
        required: true
        schema:
          type: string
          title: Oidc Discovery Endpoint
      - name: third_party_id
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/ThirdPartySSO'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Update Tenant Thirdparty Supertokens Update Tenant Thirdparty Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Update Tenant Thirdparty Supertokens Update Tenant Thirdparty Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /supertokens/update-tenant-thirdparty-custom:
    post:
      tags:
      - SUPERTOKENS
      summary: Update Tenant Thirdparty Custom
      description: 'Updates the tenant with the custom third party config

        :return: ok status and optional message.'
      operationId: update_tenant_thirdparty_custom_supertokens_update_tenant_thirdparty_custom_post
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: new_tenant
        in: query
        required: true
        schema:
          type: string
          title: New Tenant
      - name: client_id
        in: query
        required: true
        schema:
          type: string
          title: Client Id
      - name: client_secret
        in: query
        required: true
        schema:
          type: string
          title: Client Secret
      - name: oidc_discovery_endpoint
        in: query
        required: true
        schema:
          type: string
          title: Oidc Discovery Endpoint
      - name: third_party_id
        in: query
        required: true
        schema:
          type: string
          title: Third Party Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Update Tenant Thirdparty Custom Supertokens Update Tenant Thirdparty Custom Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Update Tenant Thirdparty Custom Supertokens Update Tenant Thirdparty Custom Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /supertokens/update-tenant-saml:
    post:
      tags:
      - SUPERTOKENS
      summary: Update Tenant Saml
      description: 'Updates the tenant with the SAML config

        :return: ok status and optional message.'
      operationId: update_tenant_saml_supertokens_update_tenant_saml_post
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: new_tenant
        in: query
        required: true
        schema:
          type: string
          title: New Tenant
      - name: client_id
        in: query
        required: true
        schema:
          type: string
          title: Client Id
      - name: client_secret
        in: query
        required: true
        schema:
          type: string
          title: Client Secret
      - name: provider_name
        in: query
        required: false
        schema:
          type: string
          default: SAML
          title: Provider Name
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Update Tenant Saml Supertokens Update Tenant Saml Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Update Tenant Saml Supertokens Update Tenant Saml Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /supertokens/delete-tenant-thirdparty:
    delete:
      tags:
      - SUPERTOKENS
      summary: Delete Tenant Thirdparty
      description: 'Deletes the tenant''s third party config

        :return: ok status and optional message.'
      operationId: delete_tenant_thirdparty_supertokens_delete_tenant_thirdparty_delete
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: new_tenant
        in: query
        required: true
        schema:
          type: string
          title: New Tenant
      - name: third_party_id
        in: query
        required: true
        schema:
          type: string
          title: Third Party Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Delete Tenant Thirdparty Supertokens Delete Tenant Thirdparty Delete
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Delete Tenant Thirdparty Supertokens Delete Tenant Thirdparty Delete
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /supertokens/configure/{provider}:
    post:
      tags:
      - SUPERTOKENS
      summary: Configure Sso
      description: 'Configures SSO by creating a tenant if needed and updating third-party config

        :return: ok status and optional message.'
      operationId: configure_sso_supertokens_configure__provider__post
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: provider
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/ConfigureProvider'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigureRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Configure Sso Supertokens Configure  Provider  Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Configure Sso Supertokens Configure  Provider  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ConfigureRequest:
      properties:
        client_id:
          type: string
          title: Client Id
        client_secret:
          type: string
          title: Client Secret
        oidc_url:
          type: string
          title: Oidc Url
      type: object
      required:
      - client_id
      - client_secret
      - oidc_url
      title: ConfigureRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ThirdPartySSO:
      type: string
      enum:
      - okta
      - active-directory
      title: ThirdPartySSO
    ConfigureProvider:
      type: string
      enum:
      - okta
      title: ConfigureProvider
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
