openapi: 3.1.0
info:
  title: Fast ACCOUNT_COSTS PROJECT_GOVERNANCE API
  version: 0.1.0
tags:
- name: PROJECT_GOVERNANCE
paths:
  /project_governance/check/validate:
    post:
      tags:
      - PROJECT_GOVERNANCE
      summary: Create Check
      operationId: create_check_project_governance_check_validate_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectGovernanceCreateCheckRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectGovernanceCreateCheckResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 400 Create Check Project Governance Check Validate Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 403 Create Check Project Governance Check Validate Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
      - HTTPBearer: []
  /project_governance/check:
    post:
      tags:
      - PROJECT_GOVERNANCE
      summary: Store Check
      operationId: store_check_project_governance_check_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectGovernanceStoreCheckRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 400 Store Check Project Governance Check Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 403 Store Check Project Governance Check Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
      - HTTPBearer: []
  /project_governance/checks:
    get:
      tags:
      - PROJECT_GOVERNANCE
      summary: Get Checks
      operationId: get_checks_project_governance_checks_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  additionalProperties: true
                  type: object
                type: array
                title: Response Get Checks Project Governance Checks Get
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 400 Get Checks Project Governance Checks Get
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 403 Get Checks Project Governance Checks Get
      security:
      - HTTPBearer: []
      - HTTPBearer: []
  /project_governance/check/{id}:
    patch:
      tags:
      - PROJECT_GOVERNANCE
      summary: Update Check
      operationId: update_check_project_governance_check__id__patch
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          title: Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectGovernanceUpdateCheckRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/ProjectGovernanceUpdateCheckResponse'
                - $ref: '#/components/schemas/StandardResponse'
                title: Response Update Check Project Governance Check  Id  Patch
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Update Check Project Governance Check  Id  Patch
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Update Check Project Governance Check  Id  Patch
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - PROJECT_GOVERNANCE
      summary: Delete Check
      operationId: delete_check_project_governance_check__id__delete
      deprecated: true
      security:
      - HTTPBearer: []
      - HTTPBearer: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          title: Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 400 Delete Check Project Governance Check  Id  Delete
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response 403 Delete Check Project Governance Check  Id  Delete
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /project_governance/check/run:
    post:
      tags:
      - PROJECT_GOVERNANCE
      summary: Run Checks
      operationId: run_checks_project_governance_check_run_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectGovernanceRunChecksRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectGovernanceRunChecksResponse'
        '400':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 400 Run Checks Project Governance Check Run Post
        '403':
          description: Not supported for public user
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response 403 Run Checks Project Governance Check Run Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
      - HTTPBearer: []
components:
  schemas:
    ProjectGovernanceUpdateCheckRequest:
      properties:
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        type:
          $ref: '#/components/schemas/AuditType'
      type: object
      required:
      - name
      - description
      - type
      title: ProjectGovernanceUpdateCheckRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    StandardResponse:
      properties:
        ok:
          type: boolean
          title: Ok
      type: object
      required:
      - ok
      title: StandardResponse
    AuditType:
      type: string
      enum:
      - documentation
      - tests
      - model
      - file_structure
      title: AuditType
    ProjectGovernanceCreateCheckResponse:
      properties:
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
      type: object
      required:
      - name
      - description
      title: ProjectGovernanceCreateCheckResponse
    ProjectGovernanceCreateCheckRequest:
      properties:
        description:
          type: string
          title: Description
        type:
          $ref: '#/components/schemas/AuditType'
      type: object
      required:
      - description
      - type
      title: ProjectGovernanceCreateCheckRequest
    ProjectGovernanceUpdateCheckResponse:
      properties:
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        type:
          $ref: '#/components/schemas/AuditType'
      type: object
      required:
      - name
      - description
      - type
      title: ProjectGovernanceUpdateCheckResponse
    ProjectGovernanceRunChecksResponse:
      properties:
        results:
          items:
            $ref: '#/components/schemas/CheckRunResult'
          type: array
          title: Results
      type: object
      required:
      - results
      title: ProjectGovernanceRunChecksResponse
    CheckRunResult:
      properties:
        name:
          type: string
          title: Name
        answer:
          items:
            additionalProperties: true
            type: object
          type: array
          title: Answer
        type:
          type: string
          title: Type
        id:
          type: string
          title: Id
      type: object
      required:
      - name
      - answer
      - type
      - id
      title: CheckRunResult
    ProjectGovernanceRunChecksRequest:
      properties:
        manifest_path:
          anyOf:
          - type: string
          - type: 'null'
          title: Manifest Path
        catalog_path:
          anyOf:
          - type: string
          - type: 'null'
          title: Catalog Path
        project_path:
          anyOf:
          - type: string
          - type: 'null'
          title: Project Path
        manifest:
          anyOf:
          - additionalProperties: true
            type: object
          - type: string
          - type: 'null'
          title: Manifest
        catalog:
          anyOf:
          - additionalProperties: true
            type: object
          - type: string
          - type: 'null'
          title: Catalog
        check_names:
          items:
            type: string
          type: array
          title: Check Names
      type: object
      required:
      - check_names
      title: ProjectGovernanceRunChecksRequest
    ProjectGovernanceStoreCheckRequest:
      properties:
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        type:
          $ref: '#/components/schemas/AuditType'
      type: object
      required:
      - name
      - description
      - type
      title: ProjectGovernanceStoreCheckRequest
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
servers:
- url: https://api.myaltimate.com
  description: Base URL reconciled from apis.yml
